unboxed/paapi

- .github/workflows/deploy.yml
Have the correct task-definition
> Have the correct task-definition

- README.md
- app/importers/planning_applications_importer.rb
- db/seeds.rb
- lib/tasks/import/planning_applications.rake
- spec/importers/planning_application_importer_spec.rb
- spec/importers/planning_applications_importer/address_spec.rb
- spec/importers/planning_applications_importer/planning_application_attributes_spec.rb
- spec/importers/planning_applications_importer/properties_spec.rb
- spec/support/rspec.rb
> Import by local authority

- Gemfile
- Gemfile.lock
- config/appsignal.yml
> Feature add appsignal

- README.md
- lib/tasks/import/planning_applications.rake
ARGV[0] is going to be the first value after the script
Running the script currently with
`rails import:planning_applications buckinghamshire`
and not
`rake import:planning_applications buckinghamshire`
it raises the following error
```bash
undefined method `downcase' for nil:NilClass
@local_authority_name = local_authority_name.downcase
^^^^^^^^^
```
> ARGV[0] is going to be the first value after the script

- app/importers/planning_applications_importer.rb
- db/migrate/20220920210347_add_ward_to_address.rb
- db/schema.rb
- spec/importers/planning_application_importer_spec.rb
- spec/importers/planning_applications_importer/address_spec.rb
- spec/importers/planning_applications_importer/planning_application_attributes_spec.rb
- spec/importers/planning_applications_importer/properties_spec.rb
So I've reduced this down to the minimum PR. I will then have to get S3 files in sync.
> Address modified to include ward_code and ward_name

- Dockerfile.production
Fix typo, had to be bundle config set and then install
> Fix typo, had to be bundle config set and then install

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/planning_applications_controller.rb
- app/controllers/application_controller.rb
- app/views/api/v1/planning_applications/_show.json.jbuilder
- app/views/api/v1/planning_applications/index.json.jbuilder
- config/routes.rb
- spec/requests/api/v1/planning_application_list_spec.rb
- spec/support/request_helpers.rb
Planning Application API resource:
- List all planning applications
- Search by property's uprn 
https://trello.com/c/ELQWDMp4
> Planning Application API resource

- app/importers/planning_applications_importer.rb
- app/models/property.rb
- db/migrate/20220921132714_add_property_type_to_property.rb
- db/migrate/20220921200412_add_property_code_to_property.rb
- db/schema.rb
- spec/importers/planning_application_importer_spec.rb
- spec/importers/planning_applications_importer/address_spec.rb
- spec/importers/planning_applications_importer/planning_application_attributes_spec.rb
- spec/importers/planning_applications_importer/properties_spec.rb
Property adds attribute type and code
-  "code" is property code
- "type" is property type
- "type" is a reserved word in Rails
- change the reserved word "type" to "inheritance_type" using
the method `inheritance_column`
> Property adds attribute type

- app/importers/planning_applications_importer.rb
- app/services/planning_application_creation.rb
- spec/importers/planning_applications_importer/address_spec.rb
- spec/services/planning_application_creation_spec.rb
Extract planning application creation on a service
> Extract planning application creation on a service

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/planning_applications_controller.rb
- app/controllers/application_controller.rb
- app/models/api_client.rb
- app/models/json_web_token.rb
- db/migrate/20221017130915_create_api_clients.rb
- db/schema.rb
- spec/factories/api_clients.rb
- spec/models/api_client_spec.rb
- spec/support/auth_helper.rb
API Authentication using JWT
https://trello.com/c/0QFko1OG
> API Authentication

- app/models/local_authority.rb
- spec/models/local_authority_spec.rb
Add an enum table for the local_authority name
> Add an enum table for local_authority name

- .github/workflows/deploy.yml
Deploy db-migrate on each deployment for staging
> Deploy db-migrate on each deployment for staging

- .github/workflows/deploy.yml
Mirror run db-migrate task definition for prod
> Mirror run db-migrate task definition for prod

- .github/workflows/deploy.yml
> Store output json to file

- .github/workflows/deploy.yml
> Use jq to replace image

- .github/workflows/deploy.yml
> Use image-arn as env var

- app/models/planning_application.rb
- app/models/property.rb
- db/migrate/20221103130206_add_not_null_on_more_fields.rb
- db/schema.rb
- spec/models/planning_application_spec.rb
- spec/models/property_spec.rb
Validate more fields as mandatory
> Validate more fields as mandatory

- app/controllers/api/v1/planning_applications_controller.rb
- public/api-docs/v1/_build/swagger_doc.yaml
- public/api-docs/v1/planning_applications.yaml
- spec/requests/api/v1/planning_application_list_spec.rb
Search only by uprn
https://trello.com/c/GVDiOnJe
> Search only by uprn

- app/models/property.rb
- lib/tasks/import/planning_applications.rake
- spec/models/property_spec.rb
- Correct UPRNs with exponential notation
- Correct UPRNs with missing zeros
https://trello.com/c/xRNBwr4O
> Fix uprn exponential notation

- app/controllers/api/v1/planning_applications_controller.rb
- public/api-docs/v1/_build/swagger_doc.yaml
- public/api-docs/v1/planning_applications.yaml
- spec/requests/api/v1/planning_application_list_spec.rb
Add lat and long to swagger doc
> Add lat and long to swagger doc

- public/api-docs/v1/_build/swagger_doc.yaml
- public/api-docs/v1/planning_applications.yaml
Fix swagger schema
https://trello.com/c/ziBvPvKf
> Fix swagger schema

- public/api-docs/v1/_build/swagger_doc.yaml
- public/api-docs/v1/planning_applications.yaml
Add required fields on swagger to be on json schema
> Add required fields on swagger to be on json schema

- app/models/planning_application.rb
- app/models/planning_applications_property.rb
- app/models/property.rb
- app/services/planning_application_creation.rb
- app/views/api/v1/planning_applications/_show.json.jbuilder
- db/migrate/20221121095301_create_planning_applications_properties.rb
- db/schema.rb
- public/api-docs/v1/_build/swagger_doc.yaml
- public/api-docs/v1/planning_applications.yaml
- spec/factories/planning_applications.rb
- spec/factories/planning_applications_properties.rb
- spec/importers/planning_applications_importer/properties_spec.rb
- spec/models/planning_application_spec.rb
- spec/requests/api/v1/planning_application_list_spec.rb
Has many planning_applications_property
> Has many planning_applications_property

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- app/models/address.rb
- app/models/property.rb
- db/migrate/20221207151625_address_belongs_to_property.rb
- db/migrate/20221207153653_drop_address_id_from_properties.rb
- db/migrate/20221207160407_add_unique_index_between_reference_add_local_authority_id.rb
- db/schema.rb
- spec/factories/addresses.rb
- spec/factories/properties.rb
- spec/models/property_spec.rb
> Address belongs to property

- .github/workflows/deploy-environment.yml
-  GHA remove warning for set-output
> Remove GHA set-output deploy script warnings

- .github/workflows/deploy-environment.yml
Fix deploy-environment indentation
> Fix deploy-environment indentation

- .github/workflows/deploy-environment.yml
> Move matrix on a higher level

- .github/workflows/deploy-environment.yml
> Move matrix under step name

- .github/workflows/deploy-environment.yml
Fix unrecognized named-value: matrix
> Fix unrecognized named-value: matrix

- .github/workflows/deploy-environment.yml
> Drop matrix

- .github/workflows/deploy-environment.yml
> Fix missing drop matrix

- lib/tasks/import/planning_applications.rake
- Fix typo for PlanningApplicationsImporterJob
> Fix typo for PlanningApplicationsImporterJob

- docs/_includes/header.html
- docs/sharing-data/index.md
> Updated SVG

- .github/actions/setup/action.yml
- Dockerfile.production
- Gemfile.lock
- docker-compose.yml
> Bump up bundler to 2.4.17

- Dockerfile.production
Add ruby version file to Dockerfile.production
> File .ruby-version is necessary now for Gemfile

- app/assets/stylesheets/application.bootstrap.scss
- app/javascript/application.js
- config/initializers/assets.rb
- package.json
- yarn.lock
> Remove bootstrap

- .github/workflows/deploy-environment.yml
- .github/workflows/deploy.yml
- Stops db_migrate task when rails migration fails
- Re enable matrix for all services
> Re-enable matrix [testing GH Action]

- .github/workflows/deploy-environment.yml
> Fix missing word

- .github/workflows/deploy-environment.yml
Fix issue of new matrix deploy
> Fix issue of new matrix deploy
